version: '3.7'

services:
  frontend:
    image: node:latest
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    environment:
      VUE_APP_BACKEND_URL: ${VUE_APP_BACKEND_URL}

  backend:
    build:
      context: ../backend/.
      target: dev
    ports:
      - 5000:5000
    depends_on:
      - database
      - kvstore
    volumes:
      - ../backend/src:/usr/src/app
    environment:
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_DELTA: ${JWT_EXPIRATION_DELTA}
      PIN_EXPIRATION_DELTA: ${PIN_EXPIRATION_DELTA}
      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_API_SECRET: ${MAILJET_API_SECRET}

  kvstore:
    image: redis

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
